jest.dontMock('../src/is')
const is = require('../src/is')


// for porting from QUnit
function ok(condition, reason) {
    expect(condition).toBe(true)
}

describe('Is', function() {
    it('array', function() {
        expect(is.array(function() {})).toBe(false)
        expect(is.array(is.function)).toBe(false)
        expect(is.array(setTimeout)).toBe(false)
        expect(is.array(true)).toBe(false)
        expect(is.array(false)).toBe(false)
        expect(is.array({})).toBe(false)
        expect(is.array([])).toBe(true)
        expect(is.array([1, 2])).toBe(true)
        expect(is.array({a: 3})).toBe(false)
        expect(is.array(9)).toBe(false)
        expect(is.array(0)).toBe(false)
        expect(is.array(-.1)).toBe(false)
        expect(is.array('')).toBe(false)
        expect(is.array('asdf')).toBe(false)
        expect(is.array(NaN)).toBe(false)
        expect(is.array(Infinity)).toBe(false)
        expect(is.array(undefined)).toBe(false)
        expect(is.array(null)).toBe(false)
    })
    it('object', function() {
        expect(is.object(function() {})).toBe(false)
        expect(is.object(is.function)).toBe(false)
        expect(is.object(setTimeout)).toBe(false)
        expect(is.object(true)).toBe(false)
        expect(is.object(false)).toBe(false)
        expect(is.object({})).toBe(true)
        expect(is.object([])).toBe(true)
        expect(is.object([1, 2])).toBe(true)
        expect(is.object({a: 3})).toBe(true)
        expect(is.object(9)).toBe(false)
        expect(is.object(0)).toBe(false)
        expect(is.object(-.1)).toBe(false)
        expect(is.object('')).toBe(false)
        expect(is.object('asdf')).toBe(false)
        expect(is.object(NaN)).toBe(false)
        expect(is.object(Infinity)).toBe(false)
        expect(is.object(undefined)).toBe(false)
        expect(is.object(null)).toBe(false)
    })
    it('function', function() {
        expect(is.function(function() {})).toBe(true)
        expect(is.function(is.function)).toBe(true)
        expect(is.function(setTimeout)).toBe(true)
        expect(is.function(true)).toBe(false)
        expect(is.function(false)).toBe(false)
        expect(is.function({})).toBe(false)
        expect(is.function([])).toBe(false)
        expect(is.function([1, 2])).toBe(false)
        expect(is.function({a: 3})).toBe(false)
        expect(is.function(9)).toBe(false)
        expect(is.function(0)).toBe(false)
        expect(is.function(-.1)).toBe(false)
        expect(is.function('')).toBe(false)
        expect(is.function('asdf')).toBe(false)
        expect(is.function(NaN)).toBe(false)
        expect(is.function(Infinity)).toBe(false)
        expect(is.function(undefined)).toBe(false)
        expect(is.function(null)).toBe(false)
    })
    it('boolean', function() {
        expect(is.boolean(true)).toBe(true)
        expect(is.boolean(false)).toBe(true)
        expect(is.boolean({})).toBe(false)
        expect(is.boolean([])).toBe(false)
        expect(is.boolean([1, 2])).toBe(false)
        expect(is.boolean({a: 3})).toBe(false)
        expect(is.boolean(9)).toBe(false)
        expect(is.boolean(0)).toBe(false)
        expect(is.boolean(-.1)).toBe(false)
        expect(is.boolean('')).toBe(false)
        expect(is.boolean('asdf')).toBe(false)
        expect(is.boolean(NaN)).toBe(false)
        expect(is.boolean(Infinity)).toBe(false)
        expect(is.boolean(undefined)).toBe(false)
        expect(is.boolean(null)).toBe(false)
        expect(is.boolean(function() {})).toBe(false)
    })
    it('actually a number', function() {
        ok(is.number(1))
        ok(is.number(100))
        ok(is.number(100.001))
        ok(is.number(0))
        ok(is.number(-90.3))
        ok(is.number(-90))
        ok(is.number(1 / 100000000 / 1000000 / 1000000))
        ok(is.number(100 * 100 * 100 * 100 * 100 * 100))
    })
    it('not pretending to be a number', function() {
        ok(!is.number(null))
        ok(!is.number(NaN))
        ok(!is.number(Infinity))
    })
    it('integer', function() {
        expect(is.integer(function() {})).toBe(false)
        expect(is.integer(is.function)).toBe(false)
        expect(is.integer(setTimeout)).toBe(false)
        expect(is.integer(true)).toBe(false)
        expect(is.integer(false)).toBe(false)
        expect(is.integer({})).toBe(false)
        expect(is.integer([])).toBe(false)
        expect(is.integer([1, 2])).toBe(false)
        expect(is.integer({a: 3})).toBe(false)
        expect(is.integer(9)).toBe(true)
        expect(is.integer(0)).toBe(true)
        expect(is.integer(-30)).toBe(true)
        expect(is.integer(.1)).toBe(false)
        expect(is.integer(-.1)).toBe(false)
        expect(is.integer('')).toBe(false)
        expect(is.integer('asdf')).toBe(false)
        expect(is.integer(NaN)).toBe(false)
        expect(is.integer(Infinity)).toBe(false)
        expect(is.integer(-Infinity)).toBe(false)
        expect(is.integer(undefined)).toBe(false)
        expect(is.integer(null)).toBe(false)
    })
    it('nullish', function() {
        ok(is.nullish(null), 'null')
        ok(is.nullish(undefined), undefined)
        ok(!is.nullish(''), 'empty string')
        ok(!is.nullish(0), 'zero')
        ok(!is.nullish([]), 'empty list')
        ok(!is.nullish({}), 'empty hash')
        ok(!is.nullish(NaN), 'NaN')
        expect(is.nullish(function() {})).toBe(false)
    })
    it('defined', function() {
        ok(is.defined({}), 'empty hash')
        ok(is.defined([]), 'empty list')
        ok(is.defined(''), 'empty string')
        ok(is.defined(0), 'zero')
        ok(is.defined(NaN), 'NaN')
        ok(!is.defined(undefined), 'undefined')
        ok(!is.defined(null), 'null')
        expect(is.defined(function() {})).toBe(true)
    })
    it('composes functions', function() {
        expect(is.integer.or.nullish(null)).toBe(true)
        expect(is.integer.or.nullish(undefined)).toBe(true)
        expect(is.integer.or.nullish(1)).toBe(true)
        expect(is.integer.or.nullish(1.1)).toBe(false)
        
        expect(is.nullish.or.integer(null)).toBe(true)
        expect(is.nullish.or.integer(undefined)).toBe(true)
        expect(is.nullish.or.integer(1)).toBe(true)
        expect(is.nullish.or.integer(1.1)).toBe(false)
        
        expect(is.integer.or.number(-1)).toBe(true)
        expect(is.number.or.integer(-1)).toBe(true)
        expect(is.number.or.integer('asdf')).toBe(false)
        
        expect(is.integer.or.number.or.nullish(null)).toBe(true)
        expect(is.integer.or.number.or.nullish(1.1)).toBe(true)
        expect(is.integer.or.number.or.nullish(-5)).toBe(true)
    })
})
